# get env var "SYMFONY_VERSION" from bashrc

# Check if Symfony is installed
if [ -f composer.json ]; then
    echo "Symfony is already installed"
    exit 0
fi

# Check if Symfony version is set
if [ -z "$SYMFONY_VERSION" ]; then
    echo "Symfony version is not set"
    exit 1
fi

echo "Installing Symfony $SYMFONY_VERSION"
# Install Symfony
symfony new sf --version="$SYMFONY_VERSION" --no-git
cd sf
composer config extra.symfony.docker false
composer req webapp
cd ..
# Move files to root
mv sf/* .
mv sf/.* .

# Clear docker files generated by Symfony
rm -rf sf
rm -rf compose.yaml
rm -rf compose.override.yaml

chown -R devilbox:devilbox .